yarnPath: .yarn/releases/yarn-3.0.1.cjs

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

# logFilters:
#   - code: 'YN0000'
#     pattern: '*yarn explain peer-requirements'
#     level: 'discard'

#   - code: 'YN0002'
#     level: 'discard'
