[build]
  command = "yarn build:all"
  publish = "packages/app/.next"

[build.environment]
  NODE_OPTIONS = "--max-old-space-size=8192"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*.usdz"
  [headers.values]
    # Content-Type = "model/vnd.usdz+zip"
    Content-Type = "model/vnd.pixar.usd"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.glb"
  [headers.values]
    Content-Type = "model/gltf-binary"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.gltf"
  [headers.values]
    Content-Type = "model/gltf+json"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "model/gltf+json"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
