[build]
  publish = "packages/app/.next"

[build.environment]
  NODE_OPTIONS = "--max-old-space-size=8192"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/models/tigerteen.usdz"
  [headers.values]
    Content-Type = model/vnd.usdz+zip
